# Generated by Django 3.1.1 on 2024-05-06 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='destination', to='routes.location')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='start', to='routes.location')),
            ],
        ),
    ]
